DROP TABLE "TEKST_ZAKONA";
DROP TABLE "TOKEN";

CREATE TABLE "TEKST_ZAKONA" ("TEKST_ZAKONA_ID" NUMBER NOT NULL, "TSI_ID" NUMBER, "BROJ_FILEA" NUMBER,
CONSTRAINT tekst_zakona_pk PRIMARY KEY ("TEKST_ZAKONA_ID"));

CREATE  TABLE "TOKEN" ("TOKEN_ID" NUMBER NOT NULL, "TEKST_ZAKONA_ID" NUMBER NOT NULL, "VALUE" VARCHAR2(100),
 "LEMMA" VARCHAR2(100), "TAG" VARCHAR2(100), "KATEGORIJA" VARCHAR2(1),
 CONSTRAINT token_pk PRIMARY KEY ("TOKEN_ID"));
 
ALTER TABLE "TOKEN" ADD CONSTRAINT "TOKEN_TEKST_ZAKONA_FK" FOREIGN KEY ("TEKST_ZAKONA_ID") REFERENCES "TEKST_ZAKONA" ("TEKST_ZAKONA_ID");
 
COMMIT;