DROP TABLE "TOKEN";
DROP TABLE "TEKST_ZAKONA";
DROP SEQUENCE "TEKST_ZAKONA_SEQUENCEGENERATOR";
DROP SEQUENCE "TOKEN_SEQUENCEGENERATOR";
DROP INDEX token_index;
DROP INDEX token_lemma_index;

CREATE TABLE "TEKST_ZAKONA" (
    "TEKST_ZAKONA_ID" NUMBER NOT NULL, 
    "TSI_ID" NUMBER, 
    "BROJ_FILEA" NUMBER,
    "WORD_COUNT" NUMBER DEFAULT 0,
    CONSTRAINT tekst_zakona_pk PRIMARY KEY ("TEKST_ZAKONA_ID"),
    CONSTRAINT tekst_zakona_uk UNIQUE ("BROJ_FILEA")
);
/
CREATE SEQUENCE  "TEKST_ZAKONA_SEQUENCEGENERATOR"  MINVALUE 1000 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 1000 CACHE 20 ORDER  NOCYCLE;
/
CREATE OR REPLACE TRIGGER "TEKST_ZAKONA_ON_INSERT"
  BEFORE INSERT ON "TEKST_ZAKONA"
  FOR EACH ROW
BEGIN
  SELECT "TEKST_ZAKONA_SEQUENCEGENERATOR".nextval
  INTO :new."TEKST_ZAKONA_ID"
  FROM dual;
END;
/
CREATE  TABLE "TOKEN" (
    "TOKEN_ID" NUMBER NOT NULL, 
    "TEKST_ZAKONA_ID" NUMBER NOT NULL, 
    "VALUE" VARCHAR2(250),
    "LEMMA" VARCHAR2(250), 
    "TAG" VARCHAR2(100), 
    "KATEGORIJA" VARCHAR2(1),
    "POSITION" NUMBER,
 CONSTRAINT token_pk PRIMARY KEY ("TOKEN_ID")
);
 /
ALTER TABLE "TOKEN" ADD CONSTRAINT "TOKEN_TEKST_ZAKONA_FK" FOREIGN KEY ("TEKST_ZAKONA_ID") REFERENCES "TEKST_ZAKONA" ("TEKST_ZAKONA_ID");
 /
CREATE SEQUENCE  "TOKEN_SEQUENCEGENERATOR"  MINVALUE 1 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 1000 CACHE 20 ORDER  NOCYCLE;
/
CREATE OR REPLACE TRIGGER "TOKEN_ON_INSERT"
  BEFORE INSERT ON "TOKEN"
  FOR EACH ROW
BEGIN
  SELECT "TOKEN_SEQUENCEGENERATOR".nextval
  INTO :new."TOKEN_ID"
  FROM dual;
END;
/
CREATE INDEX token_index ON token(tekst_zakona_id)
      STORAGE (INITIAL 20K
      NEXT 20k
      PCTINCREASE 75);
/
 CREATE INDEX token_lemma_index ON token(lemma)
      STORAGE (INITIAL 20K
      NEXT 20k
      PCTINCREASE 75);
/
COMMIT;