DROP TABLE "KLJUCNE_RIJECI";
DROP SEQUENCE "KLJ_RIJ_SEQUENCEGENERATOR";


CREATE TABLE "KLJUCNE_RIJECI" (
    "KLJUCNE_RIJECI_ID" NUMBER NOT NULL,
    "TSI_ID" NUMBER,
    "BROJ_FILEA" NUMBER,
    "TEKST_ZAKONA_ID" NUMBER,
    "KW_TEXTRANK" VARCHAR2(500),
    "KW_TEXTRANK_MUL_WIN_SIZE" VARCHAR2(500),
    "KW_TFIDF" VARCHAR2(500),
    "KW_TEXTRANK_IDF" VARCHAR2(500),
    "KW_TEXTRANK_MUL_WIN_IDF" VARCHAR2(500),
    CONSTRAINT kljucne_rijeci_pk PRIMARY KEY ("KLJUCNE_RIJECI_ID")
);
/
CREATE SEQUENCE "KLJ_RIJ_SEQUENCEGENERATOR" MINVALUE 1000 MAXVALUE 1000000000 INCREMENT BY 1 START WITH 1000 CACHE 20 ORDER  NOCYCLE;
/
CREATE OR REPLACE TRIGGER "KLJUCNE_RIJECI_ON_INSERT"
  BEFORE INSERT ON "KLJUCNE_RIJECI"
  FOR EACH ROW
BEGIN
  SELECT "KLJ_RIJ_SEQUENCEGENERATOR".nextval
  INTO :new."KLJUCNE_RIJECI_ID"
  FROM dual;
END;
/
INSERT INTO "KLJUCNE_RIJECI" ("TSI_ID", "BROJ_FILEA", "TEKST_ZAKONA_ID")
SELECT "TSI_ID", "BROJ_FILEA", "TEKST_ZAKONA_ID" FROM TEKST_ZAKONA;
/
COMMIT;